export const siteConfig = {
  name: "Euro International",
  tagline: "Fine Leather Goods",
  url: "https://www.eurointernational.in",
  description:
    "Euro International is a premier leather tanning and manufacturing company in Kolkata, India. We produce premium full grain, vegetable tanned, specialty and printed leathers for fashion, footwear, automotive and luxury goods industries worldwide.",
  keywords: [
    "leather manufacturer India",
    "leather tannery Kolkata",
    "premium leather goods India",
    "full grain leather supplier",
    "vegetable tanned leather India",
    "leather exporter India",
    "Euro International leather",
    "custom leather prints India",
    "sustainable leather tanning",
    "calf leather manufacturer",
    "nubuck leather India",
    "patent leather supplier",
    "leather manufacturer West Bengal",
    "leather goods Kolkata",
    "tannery India export",
  ],
  ogImage: "https://picsum.photos/seed/tanneryhero/1200/630",
  locale: "en_IN",
  phone: "+91 33 2345 6789",
  email: "info@eurointernational.com",
  address: {
    street: "Plot: 98, Zone - 10A",
    city: "Kolkata",
    region: "West Bengal",
    postalCode: "700039",
    country: "India",
    countryCode: "IN",
  },
  geo: { lat: 22.5726, lng: 88.3639 },
}
